/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnippetsRouteRouteImport } from './routes/snippets/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnippetsIndexRouteImport } from './routes/snippets/index'
import { Route as SnippetsNewRouteImport } from './routes/snippets/new'
import { Route as SnippetsIdRouteImport } from './routes/snippets/$id'

const SnippetsRouteRoute = SnippetsRouteRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIndexRoute = SnippetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SnippetsRouteRoute,
} as any)
const SnippetsNewRoute = SnippetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SnippetsRouteRoute,
} as any)
const SnippetsIdRoute = SnippetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SnippetsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/snippets': typeof SnippetsRouteRouteWithChildren
  '/snippets/$id': typeof SnippetsIdRoute
  '/snippets/new': typeof SnippetsNewRoute
  '/snippets/': typeof SnippetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/snippets/$id': typeof SnippetsIdRoute
  '/snippets/new': typeof SnippetsNewRoute
  '/snippets': typeof SnippetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/snippets': typeof SnippetsRouteRouteWithChildren
  '/snippets/$id': typeof SnippetsIdRoute
  '/snippets/new': typeof SnippetsNewRoute
  '/snippets/': typeof SnippetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/snippets' | '/snippets/$id' | '/snippets/new' | '/snippets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/snippets/$id' | '/snippets/new' | '/snippets'
  id:
    | '__root__'
    | '/'
    | '/snippets'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SnippetsRouteRoute: typeof SnippetsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/snippets': {
      id: '/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof SnippetsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/': {
      id: '/snippets/'
      path: '/'
      fullPath: '/snippets/'
      preLoaderRoute: typeof SnippetsIndexRouteImport
      parentRoute: typeof SnippetsRouteRoute
    }
    '/snippets/new': {
      id: '/snippets/new'
      path: '/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof SnippetsNewRouteImport
      parentRoute: typeof SnippetsRouteRoute
    }
    '/snippets/$id': {
      id: '/snippets/$id'
      path: '/$id'
      fullPath: '/snippets/$id'
      preLoaderRoute: typeof SnippetsIdRouteImport
      parentRoute: typeof SnippetsRouteRoute
    }
  }
}

interface SnippetsRouteRouteChildren {
  SnippetsIdRoute: typeof SnippetsIdRoute
  SnippetsNewRoute: typeof SnippetsNewRoute
  SnippetsIndexRoute: typeof SnippetsIndexRoute
}

const SnippetsRouteRouteChildren: SnippetsRouteRouteChildren = {
  SnippetsIdRoute: SnippetsIdRoute,
  SnippetsNewRoute: SnippetsNewRoute,
  SnippetsIndexRoute: SnippetsIndexRoute,
}

const SnippetsRouteRouteWithChildren = SnippetsRouteRoute._addFileChildren(
  SnippetsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SnippetsRouteRoute: SnippetsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
